/**
 * The result shape produced by every deterministic assertion.
 * Sync — no async, no LLM.
 */
export interface DeterministicAssertionResult {
  /** Whether the assertion passed. */
  passed: boolean;
  /** 1 if passed, 0 if failed. */
  score: 0 | 1;
  /** Human-readable explanation generated by the assertion. */
  reason: string;
  /** Optional message provided by the caller; shown in report on failure. */
  message: string | undefined;
  /** The name of the assertion (e.g. "toContain"). */
  assertionName: string;
  /** Literal discriminator for deterministic assertions. */
  type: 'deterministic';
  /** Wall-clock time the assertion took in milliseconds. */
  durationMs: number;
}
